### ISSUE TITLE
User Documentation

### ISSUE THREAD

**Issue by jbohrer** [IMSGlobal/openbadges-validator-core#120]
As a user of the service, I would like to have a minimal amount of documentation on how to effectively use the service and perhaps on how the service works. Perhaps some instructions can be included within the web UI, while other details might best be included in a separate document.

Example topics:
- How the service supports (or not) extensions
- Details on validation vs. verification (i.e. how extensive is verification of properties?)
- probably more

**Comment by ottonomy** [comment]
We'll use this as a catchall ticket for doc development. If a specific task needs to be broken out in the future, no problem.

* Command line usage guide
* Python module integration usage guide
* Developer's guide (updated) in readme.md
* OpenAPI doc (Swagger API definition for server)
* List of tasks that the validator runs
* General description of response format and contents (what is the graph?)

**Comment by jbohrer** [comment]
Excellent list!

**Comment by mgylling** [comment]
@jbohrer we have updated the documentation in README.MD. You can review it directly by scrolling downwards at https://github.com/IMSGlobal/openbadges-validator-core/tree/develop. Comments/suggestions welcome.

**Comment by ottonomy** [comment]
Closing, as docs are now merged. @jbohrer your comments are still welcome. If you find that the new docs are lacking, feel free to reopen this ticket with specific asks.
