### ISSUE TITLE
Support for Python3

### ISSUE THREAD

**Issue by cawmichael** [IMSGlobal/openbadges-validator-core#133]
As a user/consumer, I would like to have support for Python3.  This way, those of us with Python3 environments can use it without needing to set up a new environment with the older Python2.7.
It could also allow us to 'just plug it in' to our application and use it.
This can be especially useful for hosted environments where the Python versions available to us may be limited.

**Comment by ottonomy** [comment]
👍 willfix. Do you have some time or resources to dedicate to checking code for violations of universal python best practices and/or making great use of tox to verify py3 compliance? @cawmichael @cawjustin

**Comment by ottonomy** [comment]
@cawmichael which py3 version specifically are you hoping we'll target. I 👎 to anything prior to 3.4 for easier universal code compatibility.

**Comment by cawmichael** [comment]
@ottonomy @cawjustin I agree that aiming for 3.4+ would be ideal for more user coverage and for stability.

**Comment by ottonomy** [comment]
Ok, #159 is merged, and this is resolved. From here on out, let's get tox passing on all our mergable commits.
