### ISSUE TITLE
update release documentation for RC1

### ISSUE THREAD

**Issue by mgylling** [IMSGlobal/openbadges-validator-core#161]
Update release documentation (pypi, github, heroku) before RC1 is pushed.

**Comment by mgylling** [comment]
The heroku deployment needs to be updated to not use "badgecheck" as well (just like pypi)

**Comment by ottonomy** [comment]
@mgylling what is the new URL you propose?

**Comment by mgylling** [comment]
'ims-openbadges-validator'

**Comment by ottonomy** [comment]
Done: http://ims-openbadges-validator.herokuapp.com/

**Comment by mgylling** [comment]
Brill!

**Comment by ottonomy** [comment]
Latest docs that use the term Open Badges Validator core are in the pipeline. Finalizing the change with the package name change in PR #167
