### ISSUE TITLE
Remove early beta warning from server homepage template

### ISSUE THREAD

**Issue by ottonomy** [IMSGlobal/openbadges-validator-core#178]
```This service is currently in early beta stage. The results provided by the service cannot be used as a reliable indicator of the validity of an Open Badge, and can not not be used as proof to claim implementation conformance. Also read the disclaimer below.```

For release, this should be removed.

**Comment by mgylling** [comment]
Fixed in https://github.com/IMSGlobal/openbadges-validator-core/commit/b3cb2703f46bf1119fae4ca5efe75ced0909814b
