### ISSUE TITLE
Data URI for image value in BadgeClass?

### ISSUE THREAD

**Issue by jywsn** [IMSGlobal/openbadges-validator-core#186]
I have an assertion where the value of the`image` property within the `badge` document is a data URI.  Should this be causing any problems with the most recent validator available from pypi?  I'm getting an error:

```
{
  'messageLevel': 'ERROR',
  'name': 'IMAGE_VALIDATION',
  'node_id': u'http://127.0.0.1:8001/badge/assertion/3302786f-aa55-4162-a8fb-3ccedc36a211/badge/',
  'prop_name': 'image',
  'result': '<class \'requests.exceptions.InvalidSchema\'> ["InvalidSchema: No connection adapters were found for \'data:image/png;base64,iVBORw0KGgo...
}
```

**Comment by ottonomy** [comment]
@jywsn This is indeed a bug. Can you provide further documentation of the badgeclass JSON value that you provided to produce this bug? 

I'll try to get to this in the next round of bugfixing I submit on behalf of Concentric Sky.

**Comment by danishfastian** [comment]
Hi,

We are also facing the same error. Is it solved?

Regards,
Danish

**Comment by danishfastian** [comment]
You may get sample assertion below

https://smartcert.azurewebsites.net/OpenBadge/1/KoduGameLab-badge-award.json

Regards,
Danish
