### ISSUE TITLE
Endorsement list produces error if more than one item in array

### ISSUE THREAD

**Issue by cawmichael** [IMSGlobal/openbadges-validator-core#196]
If we have only one item in the endorsement list, validation passes but if the array has more than one item, the validation fails with:
`
Property endorsement in unknown type node http://examplesite.com/badge/2094541943/ has more than the single allowed value.
`
In other words, we pass validation with:
`
"endorsement": [
"http://example.com/endorsement/2033899500/"
]
`
but fail with:
`
"endorsement": [
"http://example.com/endorsement/2033899500/",
"http:/example.com/endorsement/1037370658/"
]
`

**Comment by ottonomy** [comment]
Thanks, @cawmichael I'll work on this ASAP

**Comment by mgylling** [comment]
@ottonomy, assigning this to @cawmichael per his request -- please let us know asap if you had started work on it. Thanks.

**Comment by cawmichael** [comment]
#200
