### ISSUE TITLE
Empty strings are valid tags

### ISSUE THREAD

**Issue by justinpitcher** [IMSGlobal/openbadges-validator-core#201]
So we ran into a bug with ingesting a badge class that was caused by an empty tag string in the array.

https://obaprod.s3-eu-west-1.amazonaws.com/mod/badge/json/v1/badgeclass/659.json

`tags: [
"Professional development",
"Technology",
"Digital Making",
""
]`

As-is, this badge validates. But I'm wondering—should it?

**Comment by ottonomy** [comment]
I think empty strings are not disallowed. (But feel free to interpret them as meaningless). The documentation for BadgeClass.tags in the Open Badges spec says: 

|property | expected type  | description |
|-- | -- | --|
| tags | Text (Multiple values allowed) | A tag that describes the type of achievement.

The Open Badges spec defines the primitive value type Text as:
> Text - A JSON string value as defined in RFC4627)

[RFC4627](https://www.ietf.org/rfc/rfc4627.txt) says:
> JSON can represent four primitive types (strings, numbers, booleans,
   and null) and two structured types (objects and arrays).
>
> A string is a sequence of zero or more Unicode characters [UNICODE].
