### ISSUE TITLE
JWS validation error

### ISSUE THREAD

**Issue by vagelisTab** [IMSGlobal/openbadges-validator-core#204]
Hello,

I created the following JWS: 

> eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.ew0KICAiQGNvbnRleHQiOiAiaHR0cHM6Ly93M2lkLm9yZy9vcGVuYmFkZ2VzL3YyIiwNCiAgInR5cGUiOiAiQXNzZXJ0aW9uIiwNCiAgImlkIjogInVybjp1dWlkOjQ5NWU0MzRmLTZjNTctNDJjMi1iZmI0LTZkOTkyODFjNjVlNyIsDQogICJyZWNpcGllbnQiOiB7DQogICAgInR5cGUiOiAiZW1haWwiLA0KICAgICJoYXNoZWQiOiB0cnVlLA0KICAgICJzYWx0IjogIjAzMjcyOTNmNTE1ZDNmMjUzZjNmIiwNCiAgICAiaWRlbnRpdHkiOiAic2hhMjU2JDNmM2YzZjc5NDk1YjNmM2YzZjNmM2YzZjNmMjA1NDNmNzE2MzIyMjE1NjFhM2YzZjY3M2Y2YzE3M2YzZjNmM2IiDQogIH0sDQogICJldmlkZW5jZSI6ICJodHRwczovL3d3dy5wZW9wbGVjZXJ0Lm9yZy9mb3ItY29ycG9yYXRpb25zL2NlcnRpZmljYXRlLXZlcmlmaWNhdGlvbi1zZXJ2aWNlIiwNCiAgImlzc3VlZE9uIjogIjIwMTgtMDUtMTRUMTU6MjE6NDIrMDM6MDAiLA0KICAiYmFkZ2UiOiAiaHR0cHM6Ly9zdGFnZS1iYWRnZXMucGVvcGxlY2VydC5vcmcvQmFkZ2VzUHJvdmlkZXIvQmFkZ2VzL0JhZGdlQ2xhc3MvNDk1ZTQzNGYtNmM1Ny00MmMyLWJmYjQtNmQ5OTI4MWM2NWU3Lmpzb24iLA0KICAidmVyaWZpY2F0aW9uIjogew0KICAgICJ0eXBlIjogIlNpZ25lZEJhZGdlIiwNCiAgICAiY3JlYXRvciI6ICJodHRwczovL3N0YWdlLWJhZGdlcy5wZW9wbGVjZXJ0Lm9yZy9CYWRnZXNQcm92aWRlci9CYWRnZXMvUHVibGljS2V5LzQ5NWU0MzRmLTZjNTctNDJjMi1iZmI0LTZkOTkyODFjNjVlNy5qc29uIg0KICB9DQp9.pWsqpe5rpFEe2svx5K9sfE9S8VkaIGpYLz-oAoC0nZsSIj8JQvCLJegVXyoltb3BECuxSUimnKL5rxtswZBZVuvR4bIM0G7fHecSn58_jmx9gVSGXNe9fcldCIpraWcfdZb4F-MM8Gz6rElLnG8-iIEkTxRLxr9t9HGUHrWSrcNpxXPRAQeJhyYsJi1LwwO8JGJMtiyq6u1AzDwKKQ2rsCnBZKLPi4bfEjykBF3G_Osf2S-4EouPu9EevZVM6ah-Jdsm9_q9FtNxTjovFQUAoEi-OwE1VKkxFre9_fHuesxQ4_pReBF7ZqUKo0wF8Trb5jmvl0CUzQYyWnZj6JzFmQ

I try to test it with the validator but i receive an invalid signature error. I verified the signature with various other tools and there was no error.

Could you please help me or guide me. This is a very urgent issue
Thanks,

**Comment by ottonomy** [comment]
Invalid signature error resolved with forthcoming code in commit 542cde74d76f5c4414e5af5376582cb918144243 Relates to #210
