### ISSUE TITLE
Validating SVG & Error with Recipient

### ISSUE THREAD

**Issue by kayaelle** [IMSGlobal/openbadges-validator-core#205]
Hey there,

I'm getting an validation error: Unknown Content-Type (Not image/png or image/svg+xml)

when using: https://openbadgesvalidator.imsglobal.org/

When using this svg for the badge class: https://cdn.rawgit.com/badgebotio/133eb1ee8dbc88c9f625440ef43fbc92/raw/a34879892cc406f5ea58428cad240f9bcb2e3625/Testbadge-image.svg

Thanks!

Tagging @ottonomy to get his thoughts.

**Comment by kayaelle** [comment]
When using the validator tool and inputting a url, it errors out with an image png or svg. It seems to recognize the image fine if a baked badge is uploaded. 

Here's an example assertion: https://gist.githubusercontent.com/badgebotio/4614803b39f580806454a0735214b221/raw

**Comment by kayaelle** [comment]
Also getting this error from same assertion:

"result": "Required property hashed not present in unknown type node https://gist.githubusercontent.com/badgebotio/46...",
                "prop_name": "hashed",
                "name": "VALIDATE_PROPERTY",
                "success": false,
                "messageLevel": "ERROR"
            }

I think this message is referring to the recipient. Note that this assertion is using type: url with a twitter account url as id.

**Comment by ottonomy** [comment]
Looks like rawgit is serving the file Content-type header correctly
`content-type: image/svg+xml;charset=utf-8`
Ah, ok
The offending line `if content_type in ['image/png', 'image/svg+xml']:`
Adding the charset string to the content-type header prevented the validator from interpreting whether it claimed to be a PNG or SVG successfully

**Comment by ottonomy** [comment]
@kayaelle the "hashed" property is required, and you haven't included it, so the validator is successfully telling you that the required property hashed is not present. Add `"hashed": false` to the IdentityObject in the assertion.

See docs on IdentityObject: https://www.imsglobal.org/sites/default/files/Badges/OBv2p0/index.html#IdentityObject
