### ISSUE TITLE
Validation error for property "verification"

### ISSUE THREAD

**Issue by MattMarked** [IMSGlobal/openbadges-validator-core#206]
My assertion's json doesn't pass the validation with one error message:
- .. Validation error for property "verification" not found in type..

but my json expose that property.

I remember that we can use verify as alias for verification, and changing the property name to verify fix it, but why? why can't i expose directly the property verification and be validated?

**Comment by ottonomy** [comment]
This is likely an issue with your context file. I wouldn't be able to tell without taking a look at the assertion it is trying to test, but probably it's using the [V1 context](https://w3id.org/openbadges/v1) where verification isn't mapped. Feel free to reopen this issue with more information if updating to either use V1 terms (as a valid 1.1 implementation), or to use V2 terms (preferred)
