### ISSUE TITLE
Problem validating v2 Open Badges with extensions

### ISSUE THREAD

**Issue by kimdhamilton** [IMSGlobal/openbadges-validator-core#207]
We've been attempting to validate our Blockcerts Open Badge v2 extensions and we're running into a problem. 

This context is actually a good example (and smaller than our full example):
https://openbadgespec.org/extensions/geoCoordinatesExtension/context.json

```
{
    "@context":{
        "obi":"https://w3id.org/openbadges#",
        "schema":"http://schema.org/",
        "extensions":"https://w3id.org/openbadges/extensions#",
        "geo":"schema:geo",
        "name":"schema:name",
        "description":"schema:description",
        "latitude":"schema:latitude",
        "longitude":"schema:longitude"
    },
    "obi:validation":[
        {
            "obi:validatesType":"extensions:GeoCoordinates",
            "obi:validationSchema":"https://w3id.org/openbadges/extensions/geoCoordinatesExtension/schema.json"
        }
    ]
}
```
What we're seeing is that the prefix value in validatesType ("extensions:" in this case), is not being expanded to the value for "extensions" defined in the context, and then the validator chokes on it.

I wanted to check if this is a known problem.

/cc: @fuerve

**Comment by ottonomy** [comment]
@kimdhamilton @fuerve Yeah, this is "known" but thanks for creating the ticket to actually formalize it. I bet this isn't the only feature gap in extension validation, but this is definitely one that should be solved. I'll get right on it and see if I can sort it out.
