### ISSUE TITLE
How to use recipient telephone number and url to verify the badge recipient?

### ISSUE THREAD

**Issue by rita-kavita** [IMSGlobal/openbadges-validator-core#208]
Hi All,

I have used the email id as recipient verification. But I have to enable the other two methods as well. 
I am not getting any thing that explains them completely.

Kindly help me asap.

**Comment by ottonomy** [comment]
@rita-kavita:

To pass in a possible recipient identifier to test, you pass in the JSON using the [Profile class from the Open Badges spec](https://openbadgespec.org/#Profile). Like this:
```json
{ 
  "email": ["myworkemail@example.com", "mypersonalemail@example.com"],
  "telephone": "+19995550123",
  "url": "https://twitter.com/myprofile"
}
```

No need to add a context url (`https://w3id.org/openbadges/v2`) or type (`Profile`) - these will be added automatically by the validator.

For a web-based experience that has somewhat more user-friendly UX, you could check out the implementation of validator UI at https://badgecheck.io (disclosure, my org wrote and operates that one)
