### ISSUE TITLE
(Signed) Assertions from bSkilled don't validate 

### ISSUE THREAD

**Issue by ottonomy** [IMSGlobal/openbadges-validator-core#210]
There's a padding issue on the signature that isn't currently validating.

**Comment by jeborsel** [comment]
Do we know if it is an encoding issue on the bSkilled part or a decoding issue on the validator side ?

**Comment by ottonomy** [comment]
@jeborsel I'm going to guess it's likely on the validator side, but I will close this ticket and reach out to you if I find otherwise. I plan to take the day Friday to work on validator issues.
