### ISSUE TITLE
What is the OB v2 signature placeholder?

### ISSUE THREAD

**Issue by indrajra** [IMSGlobal/openbadges-validator-core#215]
What is the placeholder to store the JWS signature value, per OB v2 specification? Is it always separately stored from the certificate JSON? Can you clarify please.

**Comment by amiller-ims** [comment]
Would you describe what you mean by "placeholder"?

**Comment by indrajra** [comment]
@amiller-ims, sure. Let me use an example. The spec prescribes that a `Profile` has a property `verification`, that in turn includes a property `type`. The `type` captures one of "hosted", "signed" values. Likewise, where should the signature of the certificate be stored? In simple terms, which class and which attribute is the placeholder for the signature? I find the Open Badges Vocabulary mentioning the following classes and am not sure which one could hold a signature value?
Assertion, BadgeClass, Profile (Issuer), IdentityObject, VerificationObject, Evidence, Image, Criteria, AlignmentObject, RevocationList, CryptographicKey

To give you some context, I'd like to create a certificate that has both the plain certificate data as well as its signature. JWS may not be the only algorithm, I'd like to support.

**Comment by amiller-ims** [comment]
I think I understand. And I'm pretty sure that you are using "certificate" as is a synonym for "badge", which is also a synonym for the Open Badges [Assertion](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#Assertion) class.

If I got that right, then the answer is simple: it is always stored separately.

The `Assertion` class is the top level JSON object for a badge. When you issue a badge, you can bake the assertion JSON **or** the JWS string into an image. For example,
```
var chunk = new iTXt({
  keyword: 'openbadges',
  compression: 0,
  compressionMethod: 0,
  languageTag: '',
  translatedKeyword: '',
  text: signature || JSON.stringify(assertion)
})
```
Please see the [Baking Specification](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/baking/index.html) for more examples. And note that the specification says:
> There MUST be only one <openbadges:assertion> tag in an SVG.

If you issue a badge image with both the plain text JSON and the JWS string, it is unlikely that a displayer or host would know what to do with it.

**Comment by indrajra** [comment]
Thank you @amiller-ims. Yeah, I realized I used "certificate" instead of "assertion". Special thanks for reading my thoughts on that terminology. Closing this.
