### ISSUE TITLE
UPGRADE_0_5_NODE: <type 'exceptions.UnicodeEncodeError'> ["UnicodeEncodeError: 'ascii' codec can't encode character u'\\xed' in position 3: ordinal not in range(128)\n"] 

### ISSUE THREAD

**Issue by ezavalar** [IMSGlobal/openbadges-validator-core#225]
I got this issue and this is the log file... I really want to import my badges please help!
      
  {
    "report": {
        "messages": [
            {
                "messageLevel": "ERROR", 
                "node_id": "https://miriadax.net/badge-portlet/openbadge?badge=dd7465f5-81cb-45ff-af9b-1f23166291fd&groupId=50942733&locale=es_es", 
                "name": "UPGRADE_0_5_NODE", 
                "success": false, 
                "result": "<type 'exceptions.UnicodeEncodeError'> ["UnicodeEncodeError: 'ascii' codec can't encode character u'\\xed' in position 3: ordinal not in range(128)\n"]"
            }
        ], 
        "warningCount": 0, 
        "valid": false, 
        "openBadgesVersion": "0.5", 
        "validationSubject": "https://miriadax.net/badge-portlet/openbadge?badge=dd7465f5-81cb-45ff-af9b-1f23166291fd&groupId=50942733&locale=es_es", 
        "errorCount": 1
    }, 
    "graph": [
        {
            "url": [], 
            "@context": "https://w3id.org/openbadges/v2", 
            "id": "_:b23110", 
            "email": "ezavalar_isc@hotmail.com", 
            "telephone": []
        }
    ], 
    "input": {
        "input_type": "url", 
        "value": "https://miriadax.net/badge-portlet/openbadge?badge=dd7465f5-81cb-45ff-af9b-1f23166291fd&groupId=50942733&locale=es_es"
    }
}

**Comment by pierpaolozinisal** [comment]
Hello,
I got the same issue with 16 badges by MiriadaX

This is the log of the verification of one of my badges:

    {
    "report": {
        "messages": [
            {
                "messageLevel": "ERROR", 
                "node_id": "https://miriadax.net/badge-portlet/openbadge?badge=d334ac5c-acde-4ceb-9c80-b76a9220e878&groupId=79531941&locale=es_es", 
                "name": "UPGRADE_0_5_NODE", 
                "success": false, 
                "result": "<type 'exceptions.UnicodeEncodeError'> ["UnicodeEncodeError: 'ascii' codec can't encode character u'\\xed' in position 3: ordinal not in range(128)\n"]"
            }
        ], 
        "warningCount": 0, 
        "valid": false, 
        "openBadgesVersion": "0.5", 
        "validationSubject": "https://miriadax.net/badge-portlet/openbadge?badge=d334ac5c-acde-4ceb-9c80-b76a9220e878&groupId=79531941&locale=es_es", 
        "errorCount": 1
    }, 
    "graph": [], 
    "input": {
        "input_type": "url", 
        "value": "https://miriadax.net/badge-portlet/openbadge?badge=d334ac5c-acde-4ceb-9c80-b76a9220e878&groupId=79531941&locale=es_es"
    }
}

**Comment by ezavalar** [comment]
I wrote an email to badgr's support and they answered me this:
"Hello, Ericka

We found a small problem with badges awarded by Miriadax and are working on a fix. Once we push out a fix, you will be able to upload your Miriadax badges to a Badgr backpack. This may take 1-2 weeks. Please hang on to your zipped file and retry later.

We'll let you know once the code has been updated.

Thanks in advance for your patience,

Badgr Support Team"

We must wait until it be repaired cx
