### ISSUE TITLE
Please enter valid JSON data

### ISSUE THREAD

**Issue by rikemo** [IMSGlobal/openbadges-validator-core#239]
cuando intento agregar una insignia a la mochila aparece este error ayudenme por favor!
error 
![Sin títulosdfsdf](https://user-images.githubusercontent.com/79337578/108562316-710e4980-72de-11eb-927a-dc9e30df707b.png)
"Please enter valid JSON data"

**Comment by mumitr0ll** [comment]
not needed for this particular product. This issue is for Badgr
