### ISSUE TITLE
Validation error due to "expired" SSL certificate

### ISSUE THREAD

**Issue by ForteanOrg** [IMSGlobal/openbadges-validator-core#242]
When verifying a badge the following error is displayed:

FETCH_HTTP_NODE: <class 'requests.exceptions.SSLError'> ["requests.exceptions.SSLError: HTTPSConnectionPool(host='www.msmog.nl', port=443): Max retries exceeded with url: /cemi/badges/9000001.json (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))\n"] 

This may be related to Let's Encrypt's switchover to a new root certificate. See: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ 

The certificate JSON data at https://www.msmog.nl/cemi/badges/9000001.json is valid and so is the certificate, but the Badgr software is unable to verify the certificate becaus it probably hasn't updated to the new chain of trust.

**Comment by ForteanOrg** [comment]
Resolved. Caused by a bad certification chain at the server.

**Comment by guilherme-funchal** [comment]
Hello

Im from Brazil and I work in Serpro Public  Company(https://www.serpro.gov.br/en/about-serpro), and We are testing a Badge Server and We are trying to validade our badges in IMS Validate Form and we have same problem.

I believe our certificate chain needs to be on your server, do you can help me ? 

All certification chain can be downloaded from:

https://acraiz.icpbrasil.gov.br/ICP-Brasil.crt
https://ccd.serpro.gov.br/acserpro/docs/serprov2.crt
https://ccd.serpro.gov.br/acserpro/docs/serprofinalv2.crt

https://certificados.serpro.gov.br/arserpro/pages/information/certificate_chain.jsf

**Comment by pokono** [comment]
Any suggestions for testing on local with a self signed certificate?
