### ISSUE TITLE
Unknown Content-Type (Not image/png or image/svg+xml)

### ISSUE THREAD

**Issue by francarballo** [IMSGlobal/openbadges-validator-core#248]
Hello. We have a problem with badges issued from a moodle, as we encountered the mentioned error: _Unknown Content-Type (Not image/png or image/svg+xml)_

You can verify that it is a valid badge from the following link: https://academy.net-learning.com.ar/badges/badge.php?hash=23d89946580a66ff10885968d417b203f37864e8

I share below the description of the error:

```
        {
    "graph": [],
    "input": {
        "value": "https://academy.net-learning.com.ar/badges/assertion.php?b=23d89946580a66ff10885968d417b203f37864e8&obversion=2",
        "input_type": "url"
    },
    "report": {
        "validationSubject": "https://academy.net-learning.com.ar/badges/assertion.php?b=23d89946580a66ff10885968d417b203f37864e8&obversion=2",
        "messages": [
            {
                "name": "FETCH_HTTP_NODE",
                "success": false,
                "result": "Unknown Content-Type (Not image/png or image/svg+xml). Response could not be interpreted from url https://academy.net-learning.com.ar/badges/assertion.php?b=23d89946580a66ff10885968d417b203f37864e8&obversion=2",
                "messageLevel": "ERROR"
            }
        ],
        "errorCount": 1,
        "warningCount": 0,
        "valid": false
    }
}
```

**Comment by sergio-caro** [comment]
Same here. Our badges were working back in July. Now these errors. I believe it is a Badgr error (on their side), as we did nothing new. No code changes on our side.

@francarballo any hope?

**Comment by francarballo** [comment]
Hola Sergio.
El problema de nuestro lado, venía por Cloudflare y un proxy reverso que estaba interfiriendo.
Hicimos cambios en el Moodle sacando a Cloudflare del medio, y ahora las insignias validan correctamente.

Saludos, y espero que encuentres la solución a tu inconveniente.

**Comment by sergio-caro** [comment]
> Hola Sergio. El problema de nuestro lado, venía por Cloudflare y un proxy reverso que estaba interfiriendo. Hicimos cambios en el Moodle sacando a Cloudflare del medio, y ahora las insignias validan correctamente.
> 
> Saludos, y espero que encuentres la solución a tu inconveniente.

Gracias. Seguiremos buscando a ver.

**Comment by Tuyji** [comment]
Hello,

We have also similar problem.

"IMAGE_VALIDATION: BadgeClass image of type 'image/x-ms-bmp .bmp' is unsupported"


Can you check it please ?

**Comment by andyfmiller** [comment]
BMP image files are not supported

**Comment by Arkusm** [comment]
This also happens to me if the BadgeClass id is not an image (SVG/PNG). But I wonder why ? Because there is the BadgeClass image field. Now I use the same URL for BadgeClass id and BadClass image and it works.
