### ISSUE TITLE
Rename project and move to IMS organization

### ISSUE THREAD

**Issue by mgylling** [IMSGlobal/openbadges-validator-core#62]
Rename the project (new name: openbadges-validator-core) and move to the IMS organization. The other repos in the openbadges organization should be moved as well.

**Comment by ottonomy** [comment]
What should we use for the python package name?

```py
from openbadges_validator import *
```

**Comment by mgylling** [comment]
Yes, that or openbadges_validator_core. Your thoughts?

**Comment by ViktorHaag** [comment]
If we keep the package named openbadges, and situation the validator as openbadges.validator, then we preserve the possibility for including additional functionality in the same package without breaking the validator API... that might have value?

**Comment by ottonomy** [comment]
@ViktorHaag interesting idea. I'm going to have to cogitate a little before I can give a recommendation.

There are 3 hard problems in computer science:
1. Naming things
2. Off-by-one errors

**Comment by ViktorHaag** [comment]
Yes. Naming is hard. I always heard it as, "There are two really hard problems in computer science: naming things, cache invalidation, and off-by-one errors." 8)

**Comment by ottonomy** [comment]
It's been done! Welcome to IMSGlobal/openbadges-validator-core
